name: SA
version: ${project.version}
author: Kilobytes
main:  io.github.kilobytz.sa.SA
description: Commands for SA dungeon server.
permissions:
    sa.general:
      description: Gives public commands
      default: true
    sa.donator:
      description: Gives donator commands
      default: op
    sa.warp:
      description: Gives warp commands.
      default: op
    sa.misc:
      description: Gives all misc commands.
      default: op
    sa.admin:
      description:
      default: op
commands:
  heal:
    description: Heals the user to full health.
    permission: sa.general
  spawn:
    description: Returns the user to the spawn.
    permission: sa.general
  suicide:
    description: Kills the user.
    aliases: ded
    permission: sa.general
  setpersonalspawnpoint:
    description: Sets user's spawnpoint.
    aliases: sps
    permission: sa.general
  enderchest:
    description: Opens user's Enderchest.
    aliases: ec
    permission: sa.general
  warp:
    description: Warps the user to the designated warp.
    permission: sa.warp
  setwarp:
    description: Sets the user's position to the designated warp name.
    permission: sa.warp
  delwarp:
    description: Deletes the designated warp.
    permission: sa.warp
  spawnboss:
    description: Spawns custom boss.
    permission: sa.misc
  tip:
    description: Controls server tips.
    permission: sa.admin
  rank:
    description: Edits ranks.
    permission: sa.admin
  muteall:
    description: Mutes all non-ranked players.
    permission: sa.admin
  pvptoggle:
    description: Toggles PvP on and off.
    permission: sa.admin
  worldtp:
    description: Teleports to a secondary world.
    permission: sa.warp
