name: SA
version: 2.4
author: Kilobytes
main:  io.github.kilobytz.sa.SA
description: Commands for SA dungeon server.
permissions:
    sa.general:
      description: Gives public commands
      default: true
    sa.warp:
      description: Gives warp commands.
      default: op
    sa.misc:
      description: Gives all misc commands.
      default: op
    sa.admin:
      description:
      default: op


commands:
  heal:
    description: Heals the user to full health.
    permission: sa.general
  spawn:
    description: Returns the user to the spawn.
    permission: sa.general
  ded:
    description: Kills the user.
    permission: sa.general
  warp:
    description: Warps the user to the designated warp.
    permission: sa.warp
  setwarp:
    description: Sets the user's position to the designated warp name.
    permission: sa.warp
  delwarp:
    description: Deletes the designated warp.
    permission: sa.warp
  spawnboss:
    description: Spawns custom boss.
    permission: sa.misc
  tip:
    description: Controls server tips.
    permission: sa.admin
  rank:
    description: Edits ranks.
    permission: sa.admin
